name: FarmcraftEco
main: fr.farmcraft.farmcraftEco.FarmcraftEco
version: 0.2.0
author: Farmcraft
commands:
   bank:
     description: Acceder au compte de ville.
     permission: farmcraft.bank
     usage: |
       /<command> [retrait/depot] [ville] [montant]
   debug:
     description: debug.
     usage: |
       /<command> 
   brc:
     description: Create Buyregion.
     permission: farmcraft.brc
     usage: |
       /<command> [Ville] [Nom de la region] [prix]
   rrc:
     description: Create Buyregion.
     permission: farmcraft.rrc
     usage: |
       /<command> [Ville] [Nom de la region] [prix] [Nombre de jours]
permissions:
    FarmcraftEco.user.Region.buy:
        description: Autorise les joueurs a acheter des terrains
        default : true
    FarmcraftEco.admin.Region.create:
        description: Autorise la creation des panneaux de vente de terrain
        default : op