name: FarmcraftEco
main: fr.farmcraft.farmcraftEco.FarmcraftEco
version: 0.1.0
author: Farmcraft
commands:
   bank:
     description: Acceder au compte de ville.
     permission: farmcraft.bank
     usage: |
       /<command> [retrait/depot/info] [ville] ([montant])
permissions:
   FarmcraftEco.user.bank:
     description: Acces bank
     default: false
   FarmcraftEco.admin.bank.*:
     description: Acces bank
     default: false